#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias glm='git log --topo-order --graph --pretty=format:"${_git_log_oneline_format}"'

# Better shortcut for Emacs:
function en {
    for f in "$@"
    do
        test -e $f || touch $f
    done
    open -n -a /Applications/Emacs.app "$@"
}
